apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5trnapp
  annotations:
    ves.io/workload-flavor: "ves-io-medium"
spec:
  selector:
    matchLabels:
      app: f5trnapp
  template:
    metadata:
      labels:
        app: f5trnapp
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ghcr.io/gsmythf5/f5trnapp:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        readinessProbe:
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3000"]
        livenessProbe:
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3000"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: f5trnapp
spec:
  type: ClusterIP
  selector:
    app: f5trnapp
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
---
